server:
  port: 8081
spring:
  datasource:
    quartz:
      url: jdbc:mysql://192.168.1.16:3306/Game2Element_quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: servergroup
      password: r3489nfawauiqw
      driverClassName: com.mysql.cj.jdbc.Driver
    game2element:
      url: jdbc:mysql://192.168.1.16:3306/Game2Element?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: servergroup
      password: r3489nfawauiqw
      driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
      throw-exception-if-no-handler-found: true  # 出现错误时, 直接抛出异常
  resources:
    add-mappings: false #不要为我们工程中的资源文件建立映射
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  config: classpath:log/logback-prod.xml