server:
  port: 8080
spring:
  datasource:
    game2element:
      url: jdbc:mysql://192.168.40.6:3306/Game2Element?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: servergroup
      password: tongbuserver
      driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
umeng:
  ios:
    mode: false
logging:
  config: classpath:conf/logback-dev.xml