server:
  port: 8083
spring:
  mvc:
      throw-exception-if-no-handler-found: true  # 出现错误时, 直接抛出异常
  resources:
      add-mappings: false #不要为我们工程中的资源文件建立映射
  data:
    elasticsearch:
      cluster-name: JSJ-ES #默认即为 elasticsearch
      cluster-nodes: 192.168.1.77:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
logging:
  config: conf/log/logback-prod.xml